<?php

   require '../libs/include.php';

	$colList = new DbColumnConfigList();

    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = 'id';
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'filepath';
    $tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'no';
    $tabentry['showable'] = 'no';
    $tabentry['iteratable'] = 'no'; 
    $tabentry['fieldtype'] = FIELDTYPES::_HL;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;
    $colList->addColumn(new DbColumnConfig($tabentry));

    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = null;
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'createdate';
	$tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_DP;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_DP;
    $colList->addColumn(new DbColumnConfig($tabentry));
    
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = 'incid';
    $tabentry['jointab'] = 'build_increments';
    $tabentry['realname'] = 'increment';
	$tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SS;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_SM;
    $colList->addColumn(new DbColumnConfig($tabentry));
   
    $tabentry = array();
    $tabentry['enabled'] = 'yes';    
    $tabentry['index'] = 'buildid';
    $tabentry['jointab'] = 'builds';
    $tabentry['realname'] = 'build';
    $tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SS;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;
    $colList->addColumn(new DbColumnConfig($tabentry)); 
      
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = 'tsid';
    $tabentry['jointab'] = 'testsuites';
    $tabentry['realname'] = 'tsname';
    $tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SS;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_SM;
    $colList->addColumn(new DbColumnConfig($tabentry));
    
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = 'tcid';
    $tabentry['jointab'] = 'testcases';
    $tabentry['realname'] = 'tcname';
    $tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SS;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_SM;
    $colList->addColumn(new DbColumnConfig($tabentry));
    
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = 'tlid';
    $tabentry['jointab'] = 'testlines';
    $tabentry['realname'] = 'tlname';
    $tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SS;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_SM;
    $colList->addColumn(new DbColumnConfig($tabentry)); 
  
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = 'id';
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'tcverdict';
    $tabentry['predefined'] = 'yes';
    $tabentry['value'] = null;
	$tabentry['values'] = array('ok');
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'no'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SM;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_SM;
    $colList->addColumn(new DbColumnConfig($tabentry));
    
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = null;
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'extracolumn_0';
    $tabentry['predefined'] = 'yes';
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SM;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_SM;
    $colList->addColumn(new DbColumnConfig($tabentry));

    $tabentry = array();
    $tabentry['enabled'] = 'no';
    $tabentry['index'] = null;
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'extracolumn_1';
    $tabentry['predefined'] = 'no';
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'no';
    $tabentry['showable'] = 'no';
    $tabentry['iteratable'] = 'no'; 
    $tabentry['fieldtype'] = FIELDTYPES::_IT;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;
    $colList->addColumn(new DbColumnConfig($tabentry));
    
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = null;
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'extracolumn_2';
    $tabentry['predefined'] = 'no';
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_IT;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;
    $colList->addColumn(new DbColumnConfig($tabentry));
    
    $tabentry = array();
    $tabentry['enabled'] = 'no';
    $tabentry['index'] = null;
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'extracolumn_3';
    $tabentry['predefined'] = 'no';
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'no';
    $tabentry['showable'] = 'no';
    $tabentry['iteratable'] = 'no'; 
    $tabentry['fieldtype'] = FIELDTYPES::_IT;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;
    $colList->addColumn(new DbColumnConfig($tabentry));

    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = null;
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'duration';
    $tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'no';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes';    
    $tabentry['fieldtype'] = FIELDTYPES::_IT; 
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;  
    $colList->addColumn(new DbColumnConfig($tabentry));     

    $tabentry = array();
    $tabentry['enabled'] = 'no';
    $tabentry['index'] = null;
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'shortdescription';
	$tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'no';
    $tabentry['showable'] = 'no';
    $tabentry['iteratable'] = 'no'; 
    $tabentry['fieldtype'] = FIELDTYPES::_IT;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;
    $colList->addColumn(new DbColumnConfig($tabentry));
    
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = null;
    $tabentry['jointab'] = null;
    $tabentry['realname'] = 'description';
	$tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'no';
    $tabentry['showable'] = 'no';
    $tabentry['iteratable'] = 'no'; 
    $tabentry['fieldtype'] = FIELDTYPES::_IT;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;
    $colList->addColumn(new DbColumnConfig($tabentry));
	
	$tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = 'fid';
    $tabentry['jointab'] = 'features';
    $tabentry['joinvia'] = 'tcname';
	$tabentry['jointype'] = SQLJOIN::LEFT;
    $tabentry['realname'] = 'fname';
	$tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'yes';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'yes'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SS;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_SM;
    $colList->addColumn(new DbColumnConfig($tabentry));
    
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = 'fid';
    $tabentry['jointab'] = 'features';
    $tabentry['joinvia'] = 'tcname';
	$tabentry['jointype'] = SQLJOIN::LEFT;
    $tabentry['realname'] = 'fid';
	$tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'no';
    $tabentry['showable'] = 'no';
    $tabentry['iteratable'] = 'no'; 
    $tabentry['fieldtype'] = FIELDTYPES::_SS;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_SM;
    $colList->addColumn(new DbColumnConfig($tabentry));
       
    $tabentry = array();
    $tabentry['enabled'] = 'yes';
    $tabentry['index'] = null;
    $tabentry['jointab'] = 'testcases';
    $tabentry['realname'] = 'coverage';
    $tabentry['predefined'] = null;
    $tabentry['value'] = null;
	$tabentry['values'] = array();
	$tabentry['searchable'] = 'no';
    $tabentry['showable'] = 'yes';
    $tabentry['iteratable'] = 'no';    
    $tabentry['fieldtype'] = FIELDTYPES::_IT; 
    $tabentry['valuetype'] = VALUETYPES::_REL;
    $tabentry['searcherfieldtype'] = FIELDTYPES::_IT;  
    $colList->addColumn(new DbColumnConfig($tabentry));  
    
    Config::getInstance()->updateColumnConfig($colList, 'testresults');
	
print("\n");

?>
