<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<html>
<head>
	<meta name="Description" content="A new lite test management engine used to help managing a variety of test case results." />
	<meta name="Keywords" content="testing management engine mobile relase agile sprint test case" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="author" content="Michal Krugly" />
	<title>{% block title %}A New Lite Test Management Engine{% endblock title %}</title>
{% block headerlinks %}
	<link rel="stylesheet" href="css/style_default.css?ver=1.3" type="text/css" />
	<link rel="stylesheet" href="css/jquery-ui-1.10.3.css" type="text/css" />
	<link rel="stylesheet" href="css/chosen.css" type="text/css" />	
	{% endblock headerlinks %}
	{% block headerscripts %}
	<script src="libs/js/helpers.js" type="text/javascript"></script>
	<script src="libs/js/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="libs/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
	<script src="libs/js/jquery-timepicker.js" type="text/javascript"></script>
	<script src="libs/js/chosen.jquery.js" type="text/javascript"></script>	
	<script src="libs/js/nliteme-jq.js?ver=1.5" type="text/javascript"></script>
	<script src="libs/js/tmpl.min.js"></script>
	<script src="libs/js/jquery.stickytableheaders.min.js"></script>
	{% endblock headerscripts %}
</head>
<body>
	<div id="main-container">
	  <div id="header"><img src="./images/logo_nliteme_dj.png"/></div>
		<div id="page">
	
			{% block topnav %}
			{% endblock topnav %}
			
			{% block pagecontent %}
			{% endblock pagecontent %}			
			
			<div style="clear:both;"></div>
			<div id="page-footer">
				{% block pagefooter %}
				<hr>
				<div id="footer-nav">{%block footernav %}{% endblock footernav %}</div>
				<div id="footer-copyright">
					Copyright &copy; 2012-{{ "now"|date("Y") }} by <a href="mailto:mickrugly@gmail.com?Subject=Question%20about%20NLiTe'Me">Michal Krugly</a>. All Rights Reserved.
					</br>
					Powered by Nliteme
				</div>	
				{% endblock pagefooter %}	
			</div>
		  </div>
	    </div>
	 </div>
</body>
</html>
