{% block hlrtabsettings %} {% set usepbar = 1 %} {% endblock hlrtabsettings %}
{% set pagination = content['footer'] %}
{% if (pagination is empty or pagination.getCurrentPageIndex() == 0) %}
<div>
 {% if content['label'] is not empty %} 
 <div class="toolbar-box">
   <div class="toolbar toolbar-l">
    <label>{{Text._(content['label'])}}
     {% if content['numberofrecords'] is not empty %} ({{Text._(content['numberofrecords'])}}) {% endif %}
    </label>
   </div>
 </div>
 {% endif %} 
 <div id="message-container">
  {% if messages.getMessages()|length > 0 %}
    <div id="message-container-messages">
    <ul>
    {% for message in messages.getMessages() %}
	  <li><div class="message-info-text">{{message}}</div></li>
    {% endfor %}
    </ul>
    </div>
  {% endif %}
 </div>
 <div>
	<table class="{% block scrollclass %}{% endblock scrollclass %} table-row-link table-widgie table-blue fill-parent">  
	  <thead>	
		<tr>
		{% if content['quicklinks'] is not empty %}
			<th></th>
		{% endif %}	
	    {% for column in content['header'] %}
			<th class='table-sorter'>
			{% if column.is_showable() == true %}
				{{Text._(column.getColumnRealName()|upper)}}
			{% endif %}
			</th>
		{% endfor %}
		</tr>
	  </thead>
	  <tbody>
{% endif %}	   
	    {% for record in content['body'] %}
			{% set args = record['link-args'] %}
			<tr class='tooltip-semistatic'>
				{{ block('tabquicklinks', 'common_blocks.phtml') }}
                 {% for column in content['header'] %}
					<td>
					  {% block tdtagcontent %}
				        {{ block('hlrtabtd', 'common_blocks.phtml') }}
					  {% endblock tdtagcontent %}
					</td>
				{% endfor %}
				<td class='tooltip-holder' style="display:none;">
				  <table class="table-row-link table-tooltip-1 table-widgie table-blue">
					<thead>
					  <tr>
						<th>{{Text._('tcverdict'|upper)}}</th>
						<th>{{Text._('count'|upper)}}</th>
					  </tr>
					</thead>
					<tbody>	
					 {% for inx, val in content['tooltip-header'].getColumnPredefinedValues() %}
					 {% set args = args|merge({'tcverdict':inx})%}
					 <tr>
						<td><a href="{{link.GetServerUrl()}}{{link.GetScriptName()}}?{{link.GetModifiedQueryUrl(args)}}">{{val}}</a></td>
						<td><a href="{{link.GetServerUrl()}}{{link.GetScriptName()}}?{{link.GetModifiedQueryUrl(args)}}">{{ (record['tcverdict'][inx]) ? record['tcverdict'][inx] : 0 }}</a></td>
					 </tr>
					 {% endfor %}
					</tbody>
				  </table>
				</td>
			</tr>
		{% endfor %}
{% if (pagination is empty or pagination.getCurrentPageIndex() == 0) %}		
	  </tbody>
	</table>
   {% if pagination.getNumOfPages() > 1 %}
    <script class="ajax-table-paging" type="text/javascript" data-container="table-tbody" type="text/javascript" data-page-count="{{pagination.getNumOfPages()}}" data-page="{{pagination.getCurrentPageIndex()}}" data-ajax-table-link="{{pagination.getLink().GetCurrentUrl()}}"></script>
   {% endif %}
 </div>
</div>
{% endif %}
